In [1]:
import numpy as np
from sklearn.model_selection import train_test_split

#### Lets generate some data first

In [2]:
a = np.arange(1,101)
#arange(start, stop, step): returns evenly spaced values within a given interval. By default the output is an ndarray

In [3]:
a

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [4]:
b = np.arange(1001, 1101)
b

array([1001, 1002, 1003, 1004, 1005, 1006, 1007, 1008, 1009, 1010, 1011,
       1012, 1013, 1014, 1015, 1016, 1017, 1018, 1019, 1020, 1021, 1022,
       1023, 1024, 1025, 1026, 1027, 1028, 1029, 1030, 1031, 1032, 1033,
       1034, 1035, 1036, 1037, 1038, 1039, 1040, 1041, 1042, 1043, 1044,
       1045, 1046, 1047, 1048, 1049, 1050, 1051, 1052, 1053, 1054, 1055,
       1056, 1057, 1058, 1059, 1060, 1061, 1062, 1063, 1064, 1065, 1066,
       1067, 1068, 1069, 1070, 1071, 1072, 1073, 1074, 1075, 1076, 1077,
       1078, 1079, 1080, 1081, 1082, 1083, 1084, 1085, 1086, 1087, 1088,
       1089, 1090, 1091, 1092, 1093, 1094, 1095, 1096, 1097, 1098, 1099,
       1100])

#### Spliting the data

In [5]:
#train_test_split(x): splits arrays and matrices into random train and test subsets.
train_test_split(a)

[array([20, 40, 65, 85, 76, 86, 88, 11, 77, 84, 59, 31, 13, 55, 53,  7, 15,
        70, 16, 26, 34,  6, 28, 29, 75, 54, 43, 89, 44, 38, 17, 67, 95, 32,
        22, 97, 21, 60, 46, 87, 74, 73, 66,  5, 99, 90, 63, 36, 94, 12, 92,
         8, 27, 19, 39, 71, 33, 48, 83, 23, 25, 61, 72, 68, 42, 81, 50, 98,
        57, 69,  4, 64, 49, 56, 45]),
 array([ 41,  14,  30,   2,   9,  10,  47,  91,  52,  58,  18,  62,  78,
         93,  35,  96, 100,  37,  24,   3,  82,   1,  79,  51,  80])]

In [6]:
#storing resluts into variables
a_train, a_test, b_train, b_test = train_test_split(a, b, test_size=0.2, random_state=42)

# test_size: ratio of the split
#random_state=42.  42 is a conventionally used number by the community. (It will shuffle tha data but also keep it constant)
# you can also add the shuffle argument, shuffle=False

#### Explore the results

In [7]:
a_train.shape, a_test.shape

((80,), (20,))

In [8]:
# Your R-squared is likely to change 1 or 2% by changing the split

In [9]:
b_train.shape, b_test.shape

((80,), (20,))

In [10]:
a_train

array([ 56,  89,  27,  43,  70,  16,  41,  97,  10,  73,  12,  48,  86,
        29,  94,   6,  67,  66,  36,  17,  50,  35,   8,  96,  28,  20,
        82,  26,  63,  14,  25,   4,  18,  39,   9,  79,   7,  65,  37,
        90,  57, 100,  55,  44,  51,  68,  47,  69,  62,  98,  80,  42,
        59,  49,  99,  58,  76,  33,  95,  60,  64,  85,  38,  30,   2,
        53,  22,   3,  24,  88,  92,  75,  87,  83,  21,  61,  72,  15,
        93,  52])

In [11]:
a_test

array([84, 54, 71, 46, 45, 40, 23, 81, 11,  1, 19, 31, 74, 34, 91,  5, 77,
       78, 13, 32])

In [12]:
b_train

array([1056, 1089, 1027, 1043, 1070, 1016, 1041, 1097, 1010, 1073, 1012,
       1048, 1086, 1029, 1094, 1006, 1067, 1066, 1036, 1017, 1050, 1035,
       1008, 1096, 1028, 1020, 1082, 1026, 1063, 1014, 1025, 1004, 1018,
       1039, 1009, 1079, 1007, 1065, 1037, 1090, 1057, 1100, 1055, 1044,
       1051, 1068, 1047, 1069, 1062, 1098, 1080, 1042, 1059, 1049, 1099,
       1058, 1076, 1033, 1095, 1060, 1064, 1085, 1038, 1030, 1002, 1053,
       1022, 1003, 1024, 1088, 1092, 1075, 1087, 1083, 1021, 1061, 1072,
       1015, 1093, 1052])

In [13]:
b_test

array([1084, 1054, 1071, 1046, 1045, 1040, 1023, 1081, 1011, 1001, 1019,
       1031, 1074, 1034, 1091, 1005, 1077, 1078, 1013, 1032])